# Generated by Django 5.0 on 2025-05-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_task_date_completed_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='is_complete',
        ),
    ]
