# Generated by Django 5.0 on 2025-05-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_rename_is_completed_task_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=None),
        ),
    ]
