# Generated by Django 5.0 on 2025-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_task_date_completed_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(default='Null'),
        ),
    ]
